name = "cua-admin"
main = "src/admin-worker.ts"
compatibility_date = "2026-08-08"

routes = [
  { pattern = "panel.bey2b.dpdns.org", zone_name = "bey2b.dpdns.org", custom_domain = true },
]

[[d1_databases]]
binding = "DB"
database_name = "cua-super-bot-db"
database_id = "3e1806dc-4da8-459b-943c-3664f26a1c25"

[assets]
directory = "./admin/dist"
binding = "ASSETS"
run_worker_first = true
not_found_handling = "single-page-application"
